spring:
  security:
      oauth2:
        client:
          registration:
            google:
              clientId: 709596880258-ok8elisit257eojds99dle592d15c951.apps.googleusercontent.com
              clientSecret: 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
              redirectUri: http://localhost:8080/oauth2/callback/google
              scope:
                - email
                - profile
            facebook:
              clientId: 2726427164180561
              clientSecret: 4d8d821df34e7553c0e73b1bd2244ee6
              redirectUri: http://localhost:8080/oauth2/callback/facebook
              scope:
                - email
                - public_profile  
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=name,email,picture.width(250).height(250)               
app:
  auth:
    tokenSecret: mdseapiintegrationdevelopment
    tokenExpirationMsec: 864000
    
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect